/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "service.h"

// C.1 Εύρεση Μ.Ο 
double *
average_1_svc(data *argp, struct svc_req *rqstp)
{
	static double  result;
	int size, sum;
	size = argp->y.y_len;
	sum = 0;
	
	for(int i=0;i<size;i++)
		sum += argp->y.y_val[i];

	result = (double) sum / (double) size;
	return &result;
}

// C.2 Εύρεση min max
d_ret *
min_max_1_svc(data *argp, struct svc_req *rqstp)
{
	static d_ret  result;
	int size;
	size = argp->y.y_len;
	result.a[0] = argp->y.y_val[0]; // MAX
	result.a[1] = argp->y.y_val[0]; // MIN

	for(int i=1;i<size;i++){
		if(argp->y.y_val[i]>result.a[0])
			result.a[0] = argp->y.y_val[i];
		if(argp->y.y_val[i]<result.a[1])
			result.a[1] = argp->y.y_val[i];
	}
	return &result;
}

// C.3 Eύρεση a * y
var_array *
prod_1_svc(data *argp, struct svc_req *rqstp)
{
	static var_array  result;
	int size = argp->y.y_len;

	result.j.j_val = (double *)malloc(size*sizeof(double));
	result.j.j_len = size;

	for(int i=0; i<size;i++)
		result.j.j_val[i] = argp->y.y_val[i] * argp->a;

	return &result;
}
