/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVICE_H_RPCGEN
#define _SERVICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	double a;
	struct {
		u_int y_len;
		int *y_val;
	} y;
};
typedef struct data data;

struct d_ret {
	int a[2];
};
typedef struct d_ret d_ret;

struct var_array {
	struct {
		u_int j_len;
		double *j_val;
	} j;
};
typedef struct var_array var_array;

#define Service 0x24291294
#define Srv_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define average 1
extern  double * average_1(data *, CLIENT *);
extern  double * average_1_svc(data *, struct svc_req *);
#define min_max 2
extern  d_ret * min_max_1(data *, CLIENT *);
extern  d_ret * min_max_1_svc(data *, struct svc_req *);
#define prod 3
extern  var_array * prod_1(data *, CLIENT *);
extern  var_array * prod_1_svc(data *, struct svc_req *);
extern int service_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define average 1
extern  double * average_1();
extern  double * average_1_svc();
#define min_max 2
extern  d_ret * min_max_1();
extern  d_ret * min_max_1_svc();
#define prod 3
extern  var_array * prod_1();
extern  var_array * prod_1_svc();
extern int service_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_d_ret (XDR *, d_ret*);
extern  bool_t xdr_var_array (XDR *, var_array*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_d_ret ();
extern bool_t xdr_var_array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVICE_H_RPCGEN */
